import { useRef, useState } from 'react'
import { Check, Plus, Minus, X, Sprout } from 'lucide-react'
import BottomSheet from '../common/BottomSheet'
import character from '../../assets/hankkiloop-character.png'
import { inventoryIngredients } from '../../data/inventory'
const round = (value) => Number(value.toFixed(3))
export default function StockDeductionSheet({ recipe, servings, inventory, onClose, onConfirm }) {
  const [rows, setRows] = useState(() => recipe.ingredients.map((item) => {
    const stock = inventory[item.id] ?? 0
    const deduct = Math.min(stock, round(item.quantity * servings / recipe.servings))
    return { ...item, stock, deduct, selected: stock > 0 && !item.isSeasoning }
  }))
  const [adding, setAdding] = useState(false)
  const [addId, setAddId] = useState('')
  const [error, setError] = useState('')
  const submitted = useRef(false)
  const selected = rows.filter((item) => item.selected && item.deduct > 0)
  const eligible = rows.filter((item) => item.stock > 0)
  const all = eligible.length > 0 && eligible.every((item) => item.selected)
  const patch = (id, values) => setRows((current) => current.map((item) => item.id === id ? { ...item, ...values } : item))
  const options = inventoryIngredients.filter((item) => inventory[item.id] > 0 && !rows.some((row) => row.id === item.id))
  const handleStockDeduction = (close) => {
    if (!selected.length || submitted.current) return
    try { onConfirm(selected); submitted.current = true; close() } catch (failure) { setError(failure.message) }
  }
  const checkbox = (checked, change, label, disabled = false, mixed = false) => <label className="relative flex size-6 shrink-0 items-center justify-center"><input type="checkbox" aria-label={label} checked={checked} disabled={disabled} ref={(element) => { if (element) element.indeterminate = mixed }} onChange={change} className="peer absolute inset-0 size-full cursor-pointer appearance-none rounded-md border border-[#d1d5db] bg-white checked:border-[#009b73] checked:bg-[#009b73] indeterminate:bg-[#009b73] focus-visible:outline-2 focus-visible:outline-[#006c49] disabled:cursor-default" />{(checked || mixed) && (mixed ? <Minus aria-hidden="true" className="pointer-events-none relative size-4 text-white" /> : <Check aria-hidden="true" className="pointer-events-none relative size-4 stroke-3 text-white" />)}</label>
  return <BottomSheet onClose={onClose} labelledBy="stock-title" describedBy="stock-description" label="재고 차감" header={(close) => <header className="border-b border-[#f0f1f4] px-5 pb-3"><div className="flex items-center justify-between gap-1"><div className="flex flex-wrap items-center gap-1.5"><h2 id="stock-title" className="text-lg font-bold tracking-tight">사용한 식재료 재고 차감</h2><span className="rounded-full border border-[#bbf7d0] bg-[#ecfdf5] px-2 py-1 text-[10px] font-semibold text-[#008768]">자동 계산</span></div><button type="button" onClick={close} aria-label="재고 차감 닫기" className="flex size-8 shrink-0 items-center justify-center text-[#9ca3af]"><X className="size-5" /></button></div><p id="stock-description" className="mt-1.5 text-[11px] text-[#6b7280]">요리에 소진된 재료만 골라 냉장고에서 빼드릴게요</p></header>} footer={(close) => <footer className="shrink-0 bg-white px-5 pt-2 pb-[max(20px,env(safe-area-inset-bottom))]">{error && <p role="alert" className="mb-2 text-xs text-red-600">{error}</p>}<button type="button" disabled={!selected.length || submitted.current} onClick={() => handleStockDeduction(close)} className="flex min-h-13 w-full items-center justify-center gap-2 rounded-2xl bg-[#1b4535] px-2 py-3 text-[13px] font-bold text-white shadow-lg disabled:bg-[#9caeaa]"><Check aria-hidden="true" className="size-5 shrink-0 text-[#6ee7b7]" />선택한 {selected.length}개 재료 냉장고에서 차감하기</button></footer>}>
    <div className="px-5 pt-3 pb-4">
      <aside className="flex items-center gap-3 rounded-2xl border border-[#cfead8] bg-[#f0f9f4] p-3 shadow-xs"><img src={character} alt="" className="size-12 shrink-0 rounded-xl object-cover" /><div><h3 className="flex items-center gap-1 text-sm text-[#006c49]">냉큼이의 코칭 <Sprout className="size-3.5" /></h3><p className="mt-1.5 text-xs leading-5 break-keep text-[#374151]">오늘 요리에 쓴 재료를 확인해 주세요!<br />내 냉장고 재고에서 냉큼 차감해 드릴게요.</p></div></aside>
      <div className="my-4 flex items-center gap-2">{checkbox(all, () => setRows((current) => current.map((item) => ({ ...item, selected: item.stock > 0 && !all }))), '전체 선택', !eligible.length, !all && selected.length > 0)}<span className="text-xs font-bold">전체 선택 ({eligible.length}개)</span><span className="ml-auto text-[10px] text-[#9ca3af]">조미료는 선택 해제 가능</span></div>
      <ul className="space-y-2.5">{rows.map((item) => <li key={item.id} className={`flex flex-wrap items-center gap-2 rounded-xl border p-3 ${item.selected ? 'border-[#b2f5d3] bg-[#f8fcfa]' : 'border-[#e5e7eb] bg-[#fafbfc] text-[#6b7280]'}`}>
        {checkbox(item.selected, () => patch(item.id, { selected: !item.selected }), item.name + ' 선택', item.stock <= 0)}
        <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1"><h3 className="text-sm font-bold">{item.name}</h3>{item.isSubstitute && <span className="rounded-full border border-[#bfdbfe] bg-[#eff6ff] px-1.5 py-0.5 text-[9px] text-blue-600">대체 재료</span>}<span className={`rounded-full border px-1.5 py-0.5 text-[9px] ${item.isSeasoning ? 'border-transparent bg-[#eaecef] text-[#7c8595]' : item.storageType === '실온 보관' ? 'border-[#fde68a] bg-[#fffbeb] text-[#b45309]' : 'border-[#a7f3d0] bg-[#ecfdf5] text-[#008768]'}`}>{item.isSeasoning ? '조미료' : item.storageType}</span></div>
        <p className="mt-1 text-[10px] leading-4 text-[#7c8595]">{item.stock <= 0 ? '보관 재고 없음' : !item.selected && item.isSeasoning ? '소량 사용 (재고 차감 제외 권장)' : <>{item.deduct}{item.unit} 차감 예정 · <span className={item.stock - item.deduct <= 0 && item.selected ? 'font-semibold text-[#f97316]' : 'text-[#008768]'}>{item.selected && item.stock - item.deduct <= 0 ? '소진 완료 예정' : '남은 잔여: ' + round(item.stock - (item.selected ? item.deduct : 0)) + item.unit}</span></>}</p></div>
        {item.selected ? <div className="ml-auto flex items-center rounded-lg bg-[#f1f3f5] text-xs font-bold"><button type="button" aria-label={item.name + ' 차감량 줄이기'} disabled={item.deduct <= Math.min(item.step, item.stock)} onClick={() => patch(item.id, { deduct: Math.max(Math.min(item.step, item.stock), round(item.deduct - item.step)) })} className="flex size-7 items-center justify-center disabled:opacity-30"><Minus className="size-3" /></button><output aria-label={item.name + ' 차감량'} className="min-w-8 text-center">{item.deduct}{item.unit}</output><button type="button" aria-label={item.name + ' 차감량 늘리기'} disabled={item.deduct >= item.stock} onClick={() => patch(item.id, { deduct: Math.min(item.stock, round(item.deduct + item.step)) })} className="flex size-7 items-center justify-center disabled:opacity-30"><Plus className="size-3" /></button></div> : <span className="text-[11px] text-[#9ca3af]">차감 제외</span>}
        {item.isSubstitute && <button type="button" aria-label={item.name + ' 제거'} onClick={() => setRows((current) => current.filter((row) => row.id !== item.id))} className="flex size-8 items-center justify-center text-[#9ca3af]"><X className="size-4" /></button>}
      </li>)}</ul>
      <button type="button" onClick={() => setAdding(!adding)} aria-expanded={adding} className="mt-3 flex min-h-10 w-full items-center justify-center gap-1 rounded-xl border border-dashed border-[#6ee7b7] bg-[#f5fdf9] px-2 py-2 text-[11px] font-bold text-[#006c49]"><Plus className="size-4 shrink-0" />사용한 다른 재료 직접 추가 (대체 재료 등)</button>
      {adding && <form onSubmit={(event) => { event.preventDefault(); const item = options.find((option) => option.id === addId); if (!item) return; setRows((current) => [...current, { ...item, stock: inventory[item.id], deduct: Math.min(item.quantity, inventory[item.id]), selected: true, isSubstitute: true }]); setAddId(''); setAdding(false) }} className="mt-2 flex gap-2">{options.length ? <><select aria-label="추가할 보관 재료" required value={addId} onChange={(event) => setAddId(event.target.value)} className="min-w-0 flex-1 rounded-lg border border-[#a7f3d0] p-2 text-xs"><option value="">보관 재료 선택</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name} ({inventory[item.id]}{item.unit})</option>)}</select><button type="submit" className="rounded-lg bg-[#006c49] px-3 text-xs text-white">추가</button></> : <p role="status" className="text-xs text-[#6b7280]">추가할 보관 재료가 없습니다.</p>}</form>}
    </div>
  </BottomSheet>
}
