import { BookOpen, Check, ChevronRight, CookingPot, Droplet, Image as ImageIcon, MousePointer2, Scissors, Snowflake, Sprout, Utensils } from 'lucide-react'
import character from '../../assets/hankkiloop-character.png'
import { recipes } from '../../data/recipes'
const replyIcons = { droplet: Droplet, snowflake: Snowflake, sprout: Sprout }
function SafetyResultCard({ message, onNavigate }) {
  const recipe = recipes.find((item) => item.id === message.recipeId)
  return <div className="rounded-3xl border border-[#bbf7d0] bg-[#effcf4] p-4 shadow-xs">
    <div className="flex items-center gap-3 rounded-2xl border border-[#d1fae5] bg-white/90 p-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-[#1b4535] text-white"><Check aria-hidden="true" className="size-5" /></span><div><p className="text-[11px] text-[#1b4535]">{message.summaryLabel}</p><p className="mt-0.5 text-sm leading-5">{message.summary}</p></div></div>
    <h3 className="mt-4 flex items-center gap-1 text-[13px] font-medium"><Utensils aria-hidden="true" className="size-3.5 text-[#1b4535]" />{message.heading}</h3>
    <p className="mt-2 text-[13px] leading-[22px] text-[#475569]">{message.content}</p>
    <figure className="relative mt-4 overflow-hidden rounded-2xl bg-[#e8f0e9]">{message.image ? <img src={message.image} alt={message.imageAlt} className="aspect-[2/1] w-full object-cover" /> : <div className="flex aspect-[2/1] flex-col items-center justify-center gap-2 text-[#7b8b82]"><ImageIcon aria-hidden="true" className="size-7" /><span className="text-[10px]">손질 사진 준비 중</span></div>}<figcaption className="absolute bottom-2 left-2 flex max-w-[calc(100%-16px)] items-center gap-1 rounded-lg bg-white/95 px-2 py-1 text-[10px]"><Scissors aria-hidden="true" className="size-3 shrink-0 text-[#1b4535]" />{message.caption}</figcaption></figure>
    {recipe && <div className="mt-4 flex items-center gap-2 rounded-2xl border border-[#d1fae5] bg-white p-3"><CookingPot aria-hidden="true" className="size-5 shrink-0 text-[#1b4535]" /><div className="min-w-0 flex-1"><p className="text-[13px]">{message.recipeLabel}</p><p className="mt-1 text-[11px] leading-4 text-[#7c8595]">{recipe.title} (조리 {recipe.minutes}분)</p></div><button type="button" onClick={() => onNavigate('/recipe/' + recipe.id)} className="flex min-h-11 shrink-0 items-center gap-1 rounded-xl bg-[#1b4535] px-2.5 text-[11px] text-white">레시피<ChevronRight aria-hidden="true" className="size-3" /></button></div>}
    {message.source && <div className="mt-4 flex items-start gap-1 rounded-xl border border-[#d1fae5]/70 bg-white/75 p-2.5 text-[10px] leading-[14px] text-[#7c8595]"><BookOpen aria-hidden="true" className="mt-0.5 size-3 shrink-0" />{message.source.url ? <a href={message.source.url} target="_blank" rel="noreferrer" className="underline">출처: {message.source.label}</a> : <span>출처 표시 예시: {message.source.label}</span>}</div>}
  </div>
}
export default function ChatMessage({ message, onQuickReply, onNavigate }) {
  if (message.role === 'user') return <article aria-label="사용자 메시지" className="flex items-end justify-end gap-2"><time className="shrink-0 pb-1 text-[10px] text-[#94a3b8]">{message.time}</time><p className="max-w-[74%] whitespace-pre-wrap break-words rounded-2xl bg-[#1b4535] px-3.5 py-3 text-sm leading-[22px] text-white [overflow-wrap:anywhere]">{message.content}</p></article>
  return <article aria-label={message.title} className="flex items-start gap-2.5">
    <div className="relative size-9 shrink-0 overflow-hidden rounded-full border border-[#a7f3d0] bg-[#ecfdf5]"><img src={character} alt="" className="absolute top-[-12%] left-[-2%] w-[255%] max-w-none" /></div>
    <div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2 text-xs"><h2>{message.title}</h2><span className="rounded-full border border-[#a7f3d0] bg-[#ecfdf5] px-2 py-1 text-[10px] text-[#008768]">{message.badge}</span></div>
      {message.type === 'safety-result' ? <SafetyResultCard message={message} onNavigate={onNavigate} /> : <div className="rounded-2xl border border-[#e5ece7] bg-white p-4 shadow-xs"><p className="text-[13px] leading-[22px] text-[#334155]">{message.content}</p>{message.questions && <ol className="mt-3 space-y-2 rounded-xl border border-[#edf4ef] bg-[#f5faf7] p-3">{message.questions.map((question, index) => <li key={question} className="flex items-start gap-2 text-xs leading-[18px] text-[#475569]"><span className="flex size-5 shrink-0 items-center justify-center rounded-full bg-[#d1fae5] font-bold text-[#006c49]">{index + 1}</span>{question}</li>)}</ol>}</div>}
      <time className="mt-1.5 block text-[10px] text-[#94a3b8]">{message.time}</time>
      {message.quickReplies && <div className="mt-4"><p className="mb-2 flex items-center gap-1 text-[11px] text-[#7c8595]"><MousePointer2 aria-hidden="true" className="size-3 text-[#1b4535]" />답변을 탭하여 전달하기</p><div className="flex flex-col items-start gap-2">{message.quickReplies.map((reply) => { const Icon = replyIcons[reply.icon] ?? Sprout; return <button type="button" key={reply.id} onClick={() => onQuickReply(reply.text)} className="flex max-w-full items-center gap-1.5 rounded-full border border-[#a7f3d0] bg-[#f1fcf5] px-2.5 py-2 text-left text-xs leading-4 text-[#008768]"><Icon aria-hidden="true" className="size-3.5 shrink-0" />{reply.text}</button> })}</div></div>}
    </div>
  </article>
}
